### ISSUE TITLE
Laser frame inside gazebo_cer_doublelaser.ini

### ISSUE THREAD

**Issue by morpheus1820** [robotology/cer-sim#24] opened 2020-12-22 16:17 UTC
move_base complains about having a slash inside a frame name.

`frame_id      /mobile_base_double_lidar` should probably be `frame_id      mobile_base_double_lidar`
inside
`cer-sim/gazebo/cer/conf/gazebo_cer_doublelaser.ini` (line 16). Same for `cer-sim/gazebo/cer/conf/gazebo_cer_laser_sensor.ini`, `cer-sim/gazebo/cer/conf/gazebo_cer_laser_sensor2.ini`

**Comment by DatSpace** [comment] 2021-01-15 11:55
I can confirm this as well. Removing the / (slash) solves it for all three files.

ROS spams an error about this until manually fixed.

![Screenshot from 2021-01-15 12-54-20](https://user-images.githubusercontent.com/19471755/104724453-fd9e7880-5730-11eb-987b-75247226e4ae.png)

**Comment by randaz81** [comment] 2021-01-19 08:52
I haven't found a specific guideline on the name conventions, but I think that this happens because now ROS is using TF2 instead of TF.
I'm going to commit a fix.

**Comment by randaz81** [comment] 2021-01-19 08:54
fixed by 3101000c7f786b6e72424110943b306eb187fb05

**Closed by randaz81** 2021-01-19 08:54 UTC

**Comment by morpheus1820** [comment] 2021-01-19 12:57
> I haven't found a specific guideline on the name conventions, but I think that this happens because now ROS is using TF2 instead of TF.

I think that was the reason, but I think it is safe to switch to tf2.
